### ISSUE TITLE
bug: full crash when evaluating some invalid contracts

### ISSUE THREAD

**Issue by balthazar** [warp-contracts/warp#164]
Happens when the contract in question is invalid.

For example `F2V2zXs1ylUO4hskxfNOvPlceLlk1hp_q-xEMQCPbBQ` which is missing an `await` and thus make the main process crash.

Some others:
- `aWZe5ZZIBOKZYEQuZRZRw1ElwRnZUsk3Y_4LMoN7UC4`
- `0CFuevmMBfylDZkAFV_HETPZZDh2VFRbHZnq2QGUTjw`
- `hfb7rGeMsc58G3fjnVBJaP9ogXumUE6Oc_st-QJQkLE`

**Comment by ppedziwiatr** [comment]
This happens for contracts that
1. have missing `await`
2. have a bug in code that is causing the contract code to throw an exception

In case of `F2V2zXs1ylUO4hskxfNOvPlceLlk1hp_q-xEMQCPbBQ`
<img width="682" alt="image" src="https://user-images.githubusercontent.com/84311757/174316550-e2ca92b0-c6f4-405f-824d-aea0cf44258b.png">

- missing await while calling `createTemplate` function in `swtich`
- error while calling `Object.values`, because `options.options` is undefined

**Comment by balthazar** [comment]
Yeah was hoping there would be a better solution than this, as it would mean some unhandled errors of the main code will get swallowed when the process should actually crash in order to be fixed.

**Comment by ppedziwiatr** [comment]
probably the other option for now would be to run the contract evaluation in a separate worker thread.

The isolated vm fixes this issue (ie. only the isolate crashes, not the host process), but as I've mentioned - I need a few days to implement it fully (for example - I need to manually map each of the function from the Arweave library...)

**Comment by balthazar** [comment]
Yeah will probably be the only way while waiting for the new integration, thanks

**Comment by ppedziwiatr** [comment]
Hey @balthazar , the `isolated-vm` version has been deployed in 1.1.5-beta.0.
In order to use the `isolated-vm`, set the `useIVM` in the evaluation options - like here: https://github.com/warp-contracts/warp/pull/168/files#diff-cf0d865821a10d5af3908fb2ac0246a7a7671e9460d97d7ce89946e913e88cf2R100 

Can you please test it on your side and share your feedback?

The `useIVM` should now properly handle the exception and move on..
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/84311757/175509334-9bf4955f-c39e-49ae-863d-b89087dd8d84.png">

**Comment by balthazar** [comment]
Works perfectly, thanks 😃

**Comment by ppedziwiatr** [comment]
Issue with isolated-vm - requires at least 2GB of ram to be installed via npm (i.e. the c++ compilation requires at least this amount of memory).
This is an issue for "minimal" instances (like t3.micro on AWS or basic droplets on DigitalOcean).

Re. VM2 - turns out that adding a global handler for dealing with async errors is a solution suggested be the readme - https://github.com/patriksimek/vm2#error-handling

I've created an issue whether this can be fixed/enhanced - https://github.com/patriksimek/vm2/issues/441

**Comment by balthazar** [comment]
A global error handler isn't an ideal "solution" as it simply catches any unhandled error of the process, not just vm-related errors which might result in some important errors being caught by it and overlooked.

Wouldn't there be a way to copy built binaries and headers over if the memory requirement is just at build time?

**Comment by ppedziwiatr** [comment]
yeah yeah, I'm fully aware of the issues with global handler (this _probably_ could be minimized by analyzing the stack trace (i.e. Error.stack), but still..)

Copying is one solution, dockerization - another..

The biggest issue is that in general - isolated-vm can introduce some issues for the warp library users (probably those on Windows - but - for example - I also wasn't able to install it out of the box (after adding g++ etc.) on my prev. development machine - with Fedora 34)...

**Comment by ppedziwiatr** [comment]
quickjs-emscripten - https://github.com/justjake/quickjs-emscripten/issues/70#issue-1285668067 - no luck so far.
