### ISSUE TITLE
Multiple inputs calls

### ISSUE THREAD

**Issue by angrymouse** [warp-contracts/warp#202]
Native SmartWeave supports calling of contracts using few Contract and Input entries, is it possible in Warp?

**Comment by asiaziola** [comment]
Hey :) Not sure which native SmartWeave method you have in mind?

**Comment by angrymouse** [comment]
@asiaziola Have a look - https://github.com/ArweaveTeam/SmartWeave/blob/master/src/contract-read.ts#L68
Native SmartWeave gives possibility to call multiple contracts in one transaction. Would be cool to see it in Warp

**Comment by ppedziwiatr** [comment]
> @asiaziola Have a look - https://github.com/ArweaveTeam/SmartWeave/blob/master/src/contract-read.ts#L68 Native SmartWeave gives possibility to call multiple contracts in one transaction. Would be cool to see it in Warp

It is implemented by the Warp SDK - https://github.com/warp-contracts/warp/blob/2e0001d018acdeb48294c48ee7fbb9aaa4550fe1/src/core/modules/impl/TagsParser.ts#L17

In fact - the implementation that you've pasted has been backported from our SDK to the smartweave.js :-) - after we've discovered that the original "multiple contract interactions" implementation in the smartweave.js was causing the "traditional" (i.e. single) interactions not to work properly...

The only thing that we should add is support for multiple contract interactions in our gateway - https://github.com/warp-contracts/gateway/issues/17 - so that it could index such interactions properly...
I've closed that issue cause I was pretty sure that no one is using this feature..plus, in case of warp gateway - you can use our sequencer and simply post separate interactions...so I don't see any added value here...

I'm also wondering if it isn't an issue, that (in case of "multiple contract interactions in one transaction") two different interactions for different contracts will have the exact same sortKey generated...especially for contracts that communicate with each other...

**Comment by angrymouse** [comment]
Oh, thank you! So it currently works.
