### ISSUE TITLE
Installation installs 1.1.14 by default but WarpFactory not available

### ISSUE THREAD

**Issue by dabit3** [warp-contracts/warp#208]
By following the docs, `WarpFactory` is not available in the installed module.

I had to upgrade to a newer version in order to use `WarpFactory`, unsure when it was added, but `v1.2.0-rc.1` worked for me.

**Comment by ppedziwiatr** [comment]
Hey,

we've reverted the `main` branch to the 1.1.4 version - so the 1.1.4-compatible docs are there (https://github.com/warp-contracts/warp)

the RC docs are available on `ppe/rc` branch - https://github.com/warp-contracts/warp/tree/ppe/rc

We were hoping to release the RC as the main version in a day or two, but unfortunately issues with different js module systems and web bundlers have slowed us down...

In order to install the RC version - `npm install warp-contracts@rc`
