### ISSUE TITLE
SyntaxError: Unexpected token 'export' from "readState"

### ISSUE THREAD

**Issue by 1618employment** [warp-contracts/warp#235]
<img width="551" alt="Screenshot 2022-10-04 162728" src="https://user-images.githubusercontent.com/71727929/193961271-e19fc94a-bc06-433d-bed2-fd6ff895876d.png">

Encounter this issue when running your Academy Ardit Final [demo](https://github.com/warp-contracts/academy/tree/main/warp-academy-ardit/final) 

Fails the second test 'should read Ardit state' 

using  [web bundle 1.2.13](https://unpkg.com/warp-contracts@1.2.13/bundles/web.bundle.min.js) could use an un-minified version to help trouble shoot!

**Comment by 1618employment** [comment]
never mind, some how fixed it?

**Comment by asiaziola** [comment]
Hey @1618employment! We prepared multiple Warp versions just so all the potential environments are supported. You can view the versions in `package.json` https://github.com/warp-contracts/warp/blob/main/package.json#L6

So in order to use e.g. mjs version, you can import Warp like so:

```
import { WarpFactory } from 'warp-contracts/mjs';
```

You can see some implementations (for both node and web environment) in a dedicated repository -> https://github.com/warp-contracts/bundlers
