### ISSUE TITLE
feat: add notification api

### ISSUE THREAD

**Issue by jarrvis** [warp-contracts/warp#247]
Following the quick chat with @jakub-wojciechowski at Lisbon's airport:

It would be freaking awesome if warp api supports notifications. 
Sth like:
```javascript
WarpFactory
    .forMainnet()
    .contract(theContractId)
    .subscribe(interaction => console.log(interaction)) // onChange? onInteract?
```

What we currently do at Akord is essentially to wrap warp ;) API into our internal cache which is real time db at the same time.
This helps us in querying the contract data but primarily it gives us notifications. In the end we keep the warp cache and our internal cache in sync. With every `contract.writeInteraction()` we update internal cache to notify contract subscribers.

Ideally, with notifications API at Warp we would remove our internal cache and rely on warp only.

What do you think?

**Comment by jarrvis** [comment]
Obviously eventual adding support for sockets is a bigger thing and this feature request is a long running one, if accepted.
If you need some dev time to have a look what we do on our end in detail, throw me in on a call.
Essentially our implementation of real time db is standard:
-- client -> server: http
-- server -> clients / subscribers: socket

**Comment by ppedziwiatr** [comment]
Hey @jarrvis , as you've noticed - this is probably a long running request and we would like to divide it into smaller steps.

We were thinking about adding a pub/sub feature to our sequencer - mainly for the DENs (so that DENs won't have to constantly poll the Warp GW for the interactions - which obviously does not scale in the long term).

As a very first step - the sequencer would publish a message on a given topic (related to contractTxId) that would notify the subscribers that a new interaction has been registered and they need to update their local state.

Unfortunately - until we will develop the "last_tx" feature (discussed a bit here https://github.com/warp-contracts/gateway/issues/89#issuecomment-1253819701) - it is very risky to publish the new interactions directly (and update the state based on this interaction - because subscribers won't have a way to validate whether some transaction has not been lost in the whole process).

That's why in the very first step we would simply like to simply notify the subscribers that new interactions for the given contract have been registered - and the subscribers would then simply call `contract.readState()` to update their local state.

Is such - very simplified - notification mechanism would make any sense for you.

The 2nd. step (after implementing the "last_tx" in the sequencer) would be to move from simple pub/sub to a fifo queue - the subscribers will be able to listen for the new interaction and update the state based on this new interaction directly (after validating that they already have cached state for the `new_interaction.last_tx`).

**Comment by jarrvis** [comment]
Hi @ppedziwiatr , that sounds great.
I think we can make use of step 1 - this would go to prod on our end depending on performance drop. If this is relatively low I think we can temporary sacrifice it to simplify the code by a lot.
When step 2 is live we will get back those few hundred miliseconds

**Comment by ppedziwiatr** [comment]
Hey, we're testing a new solution, the allows to subscribe for state changes.

An example of a subscription in a node.js env is available here: https://github.com/warp-contracts/warp-cache-node/blob/main/src/tools/appSyncSubscribe.js 
It requires "ws" and "warp-contracts-pubsub" libs.

An simple example of a subscription in a React app is available here: https://github.com/warp-contracts/warp-contracts-sub-react-example/blob/main/src/App.js

The channel name is simply a contractTxId.

**Comment by jarrvis** [comment]
Thanks! this is looking just great. I will hopefully help in testing by using in browser version on Akord

**Comment by ppedziwiatr** [comment]
We now have almost the "last_tx" (`last_sort_key` in fact) feature implemented in https://github.com/warp-contracts/gateway/pull/110/files - this will allow us to publish the interactions themselves - and the subscribers will be able to safely verify whether they have state cached up to the new interaction (i.e. whether latest value in their local cache is saved for `sortKey = newInteraction.lastSortKey`).

note: for now it (publishing interactions with lastSortKey) will only work for interactions saved via sequencer.

**Comment by ppedziwiatr** [comment]
@jarrvis , I'm closing this for now, in case of any issues or new, specific requests - please open a separate issue.
