### ISSUE TITLE
feat: use nested bundles in sequencer

### ISSUE THREAD

**Issue by ppedziwiatr** [warp-contracts/warp#294]
In ideal world
1. user posts some kind of id to the sequencer and sequencer assigns a sequence for this id and keeps it for some time (e.g. 1 minute). The generated sequence (the 'sortkey') is returned to the user
2. User creates a data-item with the sort-key assigned by the sequencer, the original id (that was sent to sequencer in point 1) and all the usual interaction data, signs it and sends back to the Sequencer.
3. The sequencer validates the data (i.e. whether the sort-key set in the data-item is the same sort-key that sequencer generated for the id used in point 1) and if the sequence has not expired - posts the data-item to Bundlr (as a nested bundle) and indexes it in Warp Gateway.
Note: without this "handshake" in points 1 and 2 - the generated sort-key had to be set in the nested-bundle tags.

This way we could achieve 2 things:
1. blind sequencing (i.e. the sequencer does not know any content of the transaction that it is assigning the sequence to - so it cannot manipulate the sequence based on the transaction data)
2. the sort-key is stored directly in the original data-item - this will greatly simplify interactions retrieval directly from the arweave.net gateway (e.g. if someone will decide to not use the Warp Gateway)

**Comment by jakub-wojciechowski** [comment]
Regarding point 1: 
I'd recommend using a transaction signature as the magic Id submitted by the user. It could guarantee:
a) Verification of who sends the data for ordering -> it will allow us to charge a small fee for getting a sequence - otherwise the service could be spammed or just used strategically to permanently keep a space in the transactions queue
b) Maintaining the integrity of the transaction. The transaction accepted for processing in point 3 should be the same as the one submitted for ordering. Otherwise, the user can substitute the content or even sell a place in the queue for anyone else interested in front-running and getting a priority spot without going through step 1

**Comment by ppedziwiatr** [comment]
You cannot use the transactions signature, because the user cannot sign the transaction before obtaining the sort key from the sequencer. Remember that we need to put the sortKey into the transaction/data-item's tags.
