### ISSUE TITLE
Proposal: NFT standard

### ISSUE THREAD

**Issue by koonopek** [warp-contracts/warp#332]
# Why?
We want to standardize NFTs interface, because:
- Create safer code by extending well-known standards (deploying contracts from existing source) 
- This and allows to easier create contracts which interact with each other
- It will also enable easier indexing of NFTs (for example list all NFT of user X)

# How it looks now?

Many projects adopted different standards, some examples:
* Pianity
    - Code from NFT found on their website: https://pianity.com/deep-state/altered-states  Contract: https://sonar-gzjtck03x-redstone-finance.vercel.app/?#/app/contract/XIutiOKujGI21_ywULlBeyy-L9d8goHxt0ZyUayGaDg#code
    - However in their main repository there is rust code which implements ERC1155 (https://github.com/pianity/pianity-smartcontracts-next) (looks like there want to adopt this standard in long way)
    - Interesting part of interface: 
    ```
    balanceOf(address _owner, uint256 _id)
    safeTransferFrom(address _from, address _to, uint256 _id, uint256 _value)}
    ```
* Verto
    - Another soluion https://github.com/useverto/contracts/blob/main/src/nft/faces.ts
    - Interesting part of interface: 
    ```
    balance(target: string)
    transfer(target: string, qty: number)
    ```
* Alex
    - https://github.com/ArweaveAlex/arc-pools/blob/main/src/contracts/NFT/contract.js
    - It seems more like PST then NFT, same interface as Verto:
    ```
    balance(target: string)
    transfer(target: string, qty: number)
    ```
* Atomic NFT article reference -https://atomic-assets.arweave.dev/ (for me it looks more like PST)
    ```
    balance(target: string)
    transfer(target: string, qty: number)
    ```
* Reference implementation of Atomic NFT by warp: https://github.com/warp-contracts/wrc/tree/master/contracts/atomic-nft.
* Whole interface
    ```
    Transfer {
        to: String,
        amount: u64,
    },
    TransferFrom {
        from: String,
        to: String,
        amount: u64
    },
    BalanceOf {
        target: String
    },
    TotalSupply {
    },
    Approve {
        spender: String,
        amount: u64,
    },
    Allowance {
        owner: String,
        spender: String
    },
    Evolve {
        value: String
    }
    ```
* Indexing NFTs in our warp gateway
    - https://github.com/warp-contracts/gateway/blob/main/src/gateway/router/routes/nftsOwnedByAddressRoute.ts
        
# Expected outcomes
* Mike
  - known to most of developers (something like ERC721 oraz ERC1155)
  - easly extensible, some way of extending existing contract and tweaking it to project X
     -  library?
  - reference implementation
  - documentation
  - trusted deployment via `sourceTxId`
  - Based on `kv` module or not?
  - Easily Indexable (for example additional tx.tag)

**Comment by asiaziola** [comment]
Nightmare :)
Koii was the original Atomic NFT but they abandoned the project and a lot happened since then, I guess we can safely exclude this standard version from the discussion.

Alex should be essentially an implementation of this standard https://atomic-assets.arweave.dev/
The interesting part in there is that they are using Verto Flex to make the atomic NFT tradeable (https://github.com/useverto/flex). Personally, I wouldn't consider adding it to the standard, it should be as native as possible (but it's the most used standard in the ecosystem)

The gateway indexing endpoint has been created for one specific project and is definitely deprecated, but we should also consider marking Atomic NFTs so they are easy to index and query.

**Some of the ideas i've seen on the way were:**
- `order` function - serves as a way to reserve the asset to prevent multiple people from sending payments for the same asset (which takes time and cannot be refunded)
- extending Atomic NFTs with `royalties`
- making NFT partially owned (already implemented in Warp's impl)
- an evolvable contract, though, I'm not quite familiar with the concept https://discord.com/channels/357957786904166400/819694991303639051/1065959977803599872, https://discord.com/channels/357957786904166400/819694991303639051/1066404758845411458 However, maybe it shows that there is a need for customization

**Comment by koonopek** [comment]
Okey, thanks @asiaziola for ideas:
* `order` - i don't get it it seems like part of DEX code
* `royalties` - I think it doesn't have to be part of standard
* `minting Atomic NFTs in the contract interaction` - this one sounds like creating contract from contract.

So we have to come up with some approach to propose such a standard. I think that code is not as much important as specification in case of standards. So what do you think about proposing some interface in pseudo code firstly.

(I don't get some of the methods of our implementation of NFT, that is why I wan't to specify new interface, for one contract == one NFT, so why does it have `state.balances` not just `owner`?)

My plan would look like this:
- [ ] specification (pseud code and description in academy)
- [ ] indexing
- [ ] reference implementation (js) + sourceTxId  
- [ ] library to easly extend (reuse) standard solution by other devs
- [ ] reference implementation (rust)

**Comment by ppedziwiatr** [comment]
little less conversation, little more action please...

I guess we're not in position to define contracts' standards - that's up to the Community.
